#%RAML 0.8
title: GOBI® (Global Online Bibliographic Information) Integration
baseUri: https://github.com/folio-org/mod-gobi
protocols: [ HTTPS ]
version: v1

documentation:
  - title: GOBI® (Global Online Bibliographic Information) Integration
    content: |
      GOBI® (Global Online Bibliographic Information) is the leading web-based
      acquisitions tool for finding, ordering and managing e-books and print
      books for libraries. This module allows GOBI initiated orders to be
      fulfilled by FOLIO.

schemas:
  - order: !include order.json
  - errors: !include raml-util/schemas/errors.schema
  - error.schema: !include raml-util/schemas/error.schema
  - parameters.schema: !include raml-util/schemas/parameters.schema

traits:
  - secured: !include raml-util/traits/auth.raml
  - validate: !include raml-util/traits/validation.raml

/gobi:
  displayName: GOBI Integration Service
  description: |
    Services that allow GOBI compliant orders to be processed by FOLIO
  /validate:
    displayName: Validate Access
    description: Validates the user has proper access to the module
    get:
      description: Validates the user has proper access to the module
      is: [secured]
      responses:
        204:
          description: The user is valid
        401:
          description: Not authorized to perform requested action
          body:
            text/plain:
              example: unable to get account -- unauthorized
        403:
          description: Access Denied
          body:
            text/plain:
              example: Access Denied
        500:
          description: Internal server error, e.g. due to misconfiguration
          body:
            text/plain:
              example: internal server error, contact administrator
  /orders:
    displayName: Fulfill an order
    description: Fulfill an order that is delivered in GOBI format
    post:
      description: Fulfill an order that is delivered in GOBI format
      is: [secured, validate]
      body:
        application/xml: !!null
      responses:
        201:
          description: Creates a new order within FOLIO
          body:
            application/json:
              schema: order
              example: !include examples/order.json
        400:
          description: Bad request
          body:
            text/plain:
              example: unable to process request -- constraint violation
        401:
          description: Not authorized to perform requested action
          body:
            text/plain:
              example: unable to renew loan -- unauthorized
        403:
          description: Access Denied
          body:
            text/plain:
              example: Access Denied
        500:
          description: |
            Internal server error, e.g. due to misconfiguration
          body:
            text/plain:
              example: internal server error, contact administrator
